### ISSUE TITLE
Charts and tables look bad

### ISSUE THREAD

**Issue by bengolder** [rootandrebound/roadmap-to-html#36]
CSS (and possibly HTML) should be adjusted so that charts and tables look reasonable on mobile and in browsers.

Examples:
- [VOTING RIGHTS WITH A CRIMINAL RECORD IN CALIFORNIA](https://rootandrebound.github.io/roadmap-to-html/the-building-blocks-of-reentry/driver-license-suspensions-revocations/i-have-a-criminal-record-can-i-register-to-vote-in/)

**Comment by ashleyvernon** [comment]
@cbesozzi fixes styling for charts and tables across site
