### ISSUE TITLE
Fix cross-references between pages

### ISSUE THREAD

**Issue by bengolder** [rootandrebound/roadmap-to-html#38]
Many places in the text reference other pages. Currently these links are broken when converting to HTML, and the links are not functional. Restore functionality so articles can link to each other.

**Comment by cbesozzi** [comment]
Can you provide a link to repro @bengolder ?

**Comment by bengolder** [comment]
On This page: https://rootandrebound.github.io/roadmap-to-html/employment/your-rights-against-employers/
you can see a reference to another page: `(see PG. 580)`
Similar broken references to page numbers are spread throughout

**Comment by bengolder** [comment]
I was hoping that we might be able to find some sort of html output that would structure and identify these cross references, but it appears that these links (which are interactive inside of Word) are not paired with any corresponding HTML in the output produced by mammoth:

```

**Comment by bengolder** [comment]
One possibility for addressing this:
- I currently generate each page based on the table of contents in the word document.
- each TOC entry has an associated page number that I think I currently strip out of the text. If we retained these numbers and indexed the pages by their page numbers in Word, we could create a lookup table to refer back to each page by page number.
- using this lookup table, we could search the generated HTML for text similar to `see PG. 123`, extract the number, use it to look up the page, and replace the text with an anchor tag referring to the article in question.

**Comment by bengolder** [comment]
Replace:
"PG. 580"
with
"(see here)" where the whole phrase

There will be various phrase preceding page links. for example:
- "see PG. 100"
- "something something, PG. 100"
- "on PG. 100"

**Comment by bengolder** [comment]
I've added links that go to an intermediary page index.

For example, if you follow the page links on this article:
http://roadmap.rootandrebound.org/understanding-cleaning-up-your-criminal-record/key-concepts-for-understanding-your-criminal-recor/types-of-criminal-records/background-checks/

You will arrive at the page index, on a particular page: 
http://roadmap.rootandrebound.org/page-index/#page_328

Every page may have one or more articles (defined as any line item listed in the table of contents). Therefore with a page number, we don't actually know which specific content it should link to, we can only deduce which articles began on a certain page and then show them all to the user.
