### ISSUE TITLE
Add a "this is a beta site, feedback welcome" message to the site

### ISSUE THREAD

**Issue by bengolder** [rootandrebound/roadmap-to-html#42]

**Comment by cbesozzi** [comment]
- Is there already a location to direct people for feedback like a google form?
- A button at the bottom of the navigation could work well enough 
Desktop:
![image](https://user-images.githubusercontent.com/4028371/30574170-221b3000-9cad-11e7-95d7-0dabd0261845.png)

Mobile:
![image](https://user-images.githubusercontent.com/4028371/30574185-30894fa0-9cad-11e7-9f51-69033fb1d06c.png)

**Comment by bengolder** [comment]
If possible, I'd like to put it across the top of the page, otherwise I don't think many users are like to encounter it.

I'm imagining something like this:
![feedback_beta_link](https://user-images.githubusercontent.com/451510/30675619-5e471834-9e36-11e7-8188-fda2861fdeab.png)

**Comment by bengolder** [comment]
Another example:
![screen shot 2017-09-20 at 7 28 31 pm](https://user-images.githubusercontent.com/451510/30676244-eb998610-9e39-11e7-897e-40681b3df672.png)
