### ISSUE TITLE
Main navigation does not have feedback for current location

### ISSUE THREAD

**Issue by cbesozzi** [rootandrebound/roadmap-to-html#46]
When I navigate to a chapter of the website I don't have a visual feedback of where I am currently. Best practices suggest that orientation cues can help in making a use feel in control and not feel lost.
![image](https://user-images.githubusercontent.com/4028371/30573795-a5b2de7a-9caa-11e7-9fd0-195c3f356533.png)

Suggested solution, implement a simple feedback on the active chapter link. In the example reversing the color palette.
![image](https://user-images.githubusercontent.com/4028371/30573899-57d20626-9cab-11e7-88e9-53e4bc4b10af.png)

**Comment by bengolder** [comment]
I think this is a good change 👍
