### ISSUE TITLE
Adding a css preprocessor can speed up development

### ISSUE THREAD

**Issue by cbesozzi** [rootandrebound/roadmap-to-html#48]
Adding Gulp with watch  + sass tasks can make maintaining and improving the css easier.

**Comment by bengolder** [comment]
I agree, this would be helpful, and would enable us to use a sass framework if we choose to do so

**Comment by cbesozzi** [comment]
I have a branch with this tooling partially in place:
https://github.com/cbesozzi/roadmap-to-html/tree/add-gulp-with-sass-
once the output renaming is merged I'll rebase, finish it and open a PR for feedback.

**Comment by cbesozzi** [comment]
@bengolder  @ashleyvernon merged PR, closing this issue.
