### ISSUE TITLE
Move search bar to the top of every page

### ISSUE THREAD

**Issue by bengolder** [rootandrebound/roadmap-to-html#55]
Two separate users voiced expectations that search should be immediately visible at the top of the page, regardless of where they are on the site. One user gave the example of using Chrome's default search/url bar as the kind of availability they would expect for a search bar.

My inclination is to move the search out of the side menu and into the top of every page.

This also relates to #41, as users frequently expected to encounter a page where they could more readily browse results and edit their search.

**Comment by cbesozzi** [comment]
@bengolder  Some quick mocks to align on a possible solution. Ignore styling for now, is the positioning in line with what you think?

Also,I suggest that as we take the search outside the navigation we drop the menu link on desktop. The menu is already visible by default on > 900px

Desktop:
![image](https://user-images.githubusercontent.com/4028371/30843053-8c149f26-a23b-11e7-9313-0646ca43d544.png)

Mobile
![image](https://user-images.githubusercontent.com/4028371/30843062-9d6775a0-a23b-11e7-9935-f3d9f94d8223.png)

**Comment by bengolder** [comment]
@cbesozzi Yes, I think that positioning is excellent

**Comment by cbesozzi** [comment]
@bengolder FYI
@ashleyvernon merged PR and i'm closing the issue
