### ISSUE TITLE
Home Page Design Inspiration: GOV.UK

### ISSUE THREAD

**Issue by bengolder** [rootandrebound/roadmap-to-html#64]
In thinking about #55 and #63, I looked at the home page for GOV.UK, which I think provides a nice, accessible layout and design that we could borrow from.

https://www.gov.uk/ (try it on mobile)

In particular, I like how they handle the prominence of search, the subtlety of popular pages, and the list of topics in a way that is easy to scan.

@ashleyvernon @cbesozzi what do you two think about this example as a design comparison? What would you borrow or not borrow?

**Comment by ashleyvernon** [comment]
<img width="1219" alt="screen shot 2017-09-25 at 10 04 22 pm" src="https://user-images.githubusercontent.com/18171761/30843584-f2114cf4-a23e-11e7-9d1b-4a1598736e0f.png">

I like the location of the search bar on the front page and I also like that the popular pages is in the right corner so they are distinguishable from the Chapters.  

This will also allow us to have a separate page for the search results. [#69](https://github.com/rootandrebound/roadmap-to-html/issues/69) & [68](https://github.com/rootandrebound/roadmap-to-html/issues/68)

<img width="1023" alt="screen shot 2017-09-25 at 10 18 48 pm" src="https://user-images.githubusercontent.com/18171761/30843664-8c8b8560-a23f-11e7-8d95-2d3c7401018f.png">

And I also like that the search bar goes within the nav once navigating away from the front page.

**Comment by ashleyvernon** [comment]
@bengolder I like the Design inspiration and feel like it perfectly aligns with what we are trying to create.

**Comment by bengolder** [comment]
<img width="320" alt="img_3999" src="https://user-images.githubusercontent.com/451510/31105406-d6879812-a798-11e7-8704-74e124ba0552.PNG">
<img width="320" alt="img_4001" src="https://user-images.githubusercontent.com/451510/31105407-d68a43b4-a798-11e7-89fa-5384aed8eca6.PNG">

**Comment by cbesozzi** [comment]
@bengolder I shipped a version of #55 that we can iterate over to get to an experience similar to UK.gov 
I think it is worth to explore the possible result in Sketch first before making any change.
